### PR TITLE
feat: mongo containers

### PR DESCRIPTION
**Pull request by MartinAAcebeyL**
This project offers a simplified solution to efficiently build and manage MongoDB containers. Using Docker latest and alpine images, users can quickly configure and deploy MongoDB instances, adapting environment variables according to their needs. Additionally, a Makefile with convenient shortcuts is provided to simplify common operations

### CODE REVIEW

**Comment by xmnlab** [comment]
hey @MartinAAcebeyL ! sorry I missed the notification for this PR!
really sorry about that.

I am adding some comments here

**Review by xmnlab — CHANGES_REQUESTED** [review]
in general, it looks good to me. 
thanks for working on that!

some comments:

* all the files are missing a new line at the end of the file. that is a good practice in general, you probably should configure your IDE to do automatically for you :)
* normally we don't have files or folder with upper case letter .. so it would be probably be better to have `mongo` instead of `Mongo`


extra comments that would maybe make this PR better:

* use makim instead of makefile
* use sugar instead of docker-compose directly, so it would add a new layer and you can configure easily  the services

**Comment by MartinAAcebeyL** [comment]
No problem at all, and thank you for the feedback and suggestions! I've made the necessary adjustments based on your comments. Here’s a summary of the changes:

- Added new lines at the end of all files.
- Corrected folder names to use lowercase.
- Updated the README and comments in each file to English.

Apologies for not including 'makim' and 'sugar' this time. I'll explore integrating them in future updates.

**Comment by xmnlab** [comment]
thanks for working on that @MartinAAcebeyL !
appreciate that

**Pull request merged**
